app_name: Ai Meme Maker
app_subtitle: Capture or upload an image and let the AI turn your photos into hilarious memes.
app_download: https://apps.apple.com/app/ai-meme-maker-pro/id6468994591
app_github: https://play.google.com/store/apps/details?id=com.prime.aimememaker
app_id: id6468994591
email: hi@aimememaker.app
app_icon: /assets/icon.png
favicon: /assets/icon.png

made_by:

links:
  - title: Terms
    url: https://adprime.ltd
  - title: Privacy
    url: https://adprime.ltd

app_description: |
    Welcome to Ai Meme Maker, Your One-Stop Solution for Instant Meme Creation!

    ## Instantly Create Memes with AI

    1. **Capture or Upload**: Snap a photo or choose one from your gallery.
    2. **AI-Powered**: Our cutting-edge AI technology crafts memes in seconds.
    3. **Download or Share**: Save your meme or share it directly on social media.

    ## Why Choose Ai Meme Maker?

    - **User-Friendly Interface**: No complicated steps, create memes effortlessly.
    - **Quick and Unique**: Memes are not only created in seconds but are also unique.
    - **One-Click Sharing**: Share your Ai-generated memes instantly to your social media platforms.
  
    <br>Our AI Meme Maker ensures your memes stand out, boosting your social media engagement and bringing 'Ha Ha' and 'LOLs' into your life!

    ## The Power of AI in Meme Creation

    What sets Ai Meme Maker apart is its AI technology. We don't just add text to images; we create memes that understand the context, ensuring they are relevant and hilarious. Transform your photos into memes that resonate with your emotions.

    ## Reach Out to Us

    Have questions or suggestions? Contact us at [hi@aimememaker.app](mailto:hi@aimememaker.app).




####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

plugins:
  - jekyll-postcss

exclude:
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - README.md
  - postcss.config.js
  - .gitignore
  - node_modules

markdown: kramdown

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: "assets/screenshots"
    values:
      screenshot: true
